apache/commons-compress

src/main/java/org/apache/commons/compress/archivers/ar/ArArchiveInputStream.java, src/test/java/org/apache/commons/compress/archivers/ar/ArArchiveInputStreamTest.java
The original code appears to be checking for end-of-file
using the InputStream.available() method.
This however, misunderstands the InputStream API. The available()
method only returns an estimate, and cannot be used
to check for the remaining bytes in the file. From the documentation:
> Returns an estimate of the number of bytes that can be read (or
> skipped over) from this input stream without blocking by the next
> invocation of a method for this input stream. The next invocation
> might be the same thread or another thread.  A single read or skip of this
> many bytes will not block, but may read or skip fewer bytes.
> **Note that while some implementations of InputStream will return
> the total number of bytes in the stream, many will not.**  It is
> never correct to use the return …
=> Correct EOF check in ArArchiveInputStream

src/main/java/org/apache/commons/compress/archivers/arj/ArjArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/sevenz/SevenZOutputFile.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveEntry.java
Since Java 6, calling toArray with an array of size is faster than calling it with the size of the array (https://shipilev.net/blog/2016/arrays-wisdom-ancients/). This is also a PMD recommendation: https://pmd.github.io/latest/pmd_rules_java_performance.html#optimizabletoarraycall 
I changed this in the code.
=> Performance Improvement: Call toArray with 0 Array Size

src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveEntry.java
Just a trivial change to `TarArchiveEntry#getModTime()`
=> (doc) minor javadoc fix

src/main/java/org/apache/commons/compress/compressors/zstandard/ZstdCompressorOutputStream.java
The zstd-jni was updated to 1.4.4-7, and some constructors of ZstdOutputStream were deprecated.
This PR fix them as the comment was recommended :
/**
*  @deprecated
*  Use ZstdOutputStream() or ZstdOutputStream(level) and set the other params with the setters
**/
=> Deprecated constructors of ZstdOutputStream fix

src/main/java/org/apache/commons/compress/archivers/sevenz/SevenZFile.java, src/main/java/org/apache/commons/compress/utils/ChecksumVerifyingInputStream.java, src/test/java/org/apache/commons/compress/archivers/sevenz/SevenZFileTest.java
There are some problems in my PR about random access of 7z [#83](COMPRESS-342 random access of 7z files) :
1. I was thinking that the `currentFolderInputStream` can be repositioned by changing the position of the `channel`, which turns out to be impossible. This PR fixesit by reopening the `currentFolderInputStream`.
2. There are 2 ways to access the content of a 7z archive now : by sequential access(getNextEntry) and by random access(getInputStream). They may be used one after another. So there're some conditions we need to deal with :
2.1 In a random access, if `currentEntryIndex` == `entryIndex` && the entry has not been read yet :
This means the input stream of the entry we want has already been put in the `deferredBlockStreams` as the last array member. We SHOULD NOT build a new …
=> COMPRESS-505 : bug fix for random access of 7z

pom.xml, src/test/java/org/apache/commons/compress/compressors/z/ZCompressorInputStreamTest.java
Noticed this test is skipped while checking the unit tests log. The mockito dependency was transitive before.
Is there a Jira ticket needed for a change like this?
=> COMPRESS-520: Implement ZCompressorInputStreamTest without powermock

src/main/java/org/apache/commons/compress/archivers/ar/ArArchiveOutputStream.java, src/main/java/org/apache/commons/compress/archivers/sevenz/SevenZFile.java, src/main/java/org/apache/commons/compress/archivers/sevenz/SevenZOutputFile.java, src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveOutputStream.java, src/main/java/org/apache/commons/compress/archivers/zip/AbstractUnicodeExtraField.java, src/main/java/org/apache/commons/compress/compressors/gzip/GzipCompressorInputStream.java, src/main/java/org/apache/commons/compress/compressors/gzip/GzipCompressorOutputStream.java, src/main/java/org/apache/commons/compress/utils/ArchiveUtils.java, src/test/java/org/apache/commons/compress/archivers/TarTestCase.java, src/test/java/org/apache/commons/compress/archivers/sevenz/SevenZFileTest.java, src/test/java/org/apache/commons/compress/archivers/tar/TarArchiveInputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/tar/TarArchiveOutputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/tar/TarUtilsTest.java, src/test/java/org/apache/commons/compress/archivers/zip/DataDescriptorTest.java, src/test/java/org/apache/commons/compress/archivers/zip/UTF8ZipFilesTest.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipFileTest.java, src/test/java/org/apache/commons/compress/compressors/CompressorStreamFactoryRoundtripTest.java, src/test/java/org/apache/commons/compress/compressors/lz77support/LZ77CompressorTest.java, src/test/java/org/apache/commons/compress/utils/CharsetsTest.java, src/test/java/org/apache/commons/compress/utils/SeekableInMemoryByteChannelTest.java
In most cases using StandardCharsets is faster.
You can get more information at `decode(String charsetName, byte[] ba, int off, int len)` and `decode(Charset cs, byte[] ba, int off, int len)` in class java.lang.StringCoding
=> [COMPRESS-534] use StandardCharsets.

src/main/java/org/apache/commons/compress/compressors/bzip2/BZip2CompressorOutputStream.java
Hi.
Can we add a break here?
Also, should we try implement a data structure or something for doing this? a loop like this sounds slow.
If you don't mind I will give it a try several hours later (if I still have some time).
=> [COMPRESS-535] maybe we can add a break here

src/main/java/org/apache/commons/compress/archivers/cpio/CpioArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/cpio/CpioArchiveOutputStream.java, src/main/java/org/apache/commons/compress/archivers/cpio/CpioUtil.java, src/main/java/org/apache/commons/compress/archivers/sevenz/SevenZFile.java, src/main/java/org/apache/commons/compress/archivers/zip/X0017_StrongEncryptionHeader.java, src/main/java/org/apache/commons/compress/compressors/bzip2/CRC.java, src/test/java/org/apache/commons/compress/archivers/tar/TarUtilsTest.java, src/test/java/org/apache/commons/compress/compressors/bzip2/PythonTruncatedBzip2Test.java, src/test/java/org/apache/commons/compress/utils/FixedLengthBlockOutputStreamTest.java
from both `byte a[]` and `byte[] a` to only `byte[] a`
=> unitized array styles.

src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveEntry.java
to avoid Date() object creation thus faster.
=> use System.currentTimeMillis instead of new Date().getTime

pom.xml, src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveEntry.java, src/test/java/org/apache/commons/compress/AbstractTestCase.java, src/test/java/org/apache/commons/compress/archivers/tar/TarArchiveEntryTest.java, src/test/java/org/apache/commons/compress/archivers/tar/TarMemoryFileSystemTest.java
I wan't to use the NIO API more in my application and therefore would need some additional methods which support the NIO API. Found this already existent issue and thought this would be a good starting point.
The first commit handles the internal migration to the Path object. The second adds additional information to the TarArchiveEntry. Before adding more functionality (e.g. symlinks) I would like to get some feedback for the error handling. Since the old File constructor didn't throw an exception the now delegating constructor also shouldn't throw an exception. But with NIO most file access operations are throwing one.
=> COMPRESS-404: Use java.nio.Path in TarArchiveEntry

src/main/java/org/apache/commons/compress/archivers/zip/ZipEightByteInteger.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipLong.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipShort.java
Or, is it for special optimization strategy?
=> remove `== null` as it is covered by `instance of`

src/main/java/org/apache/commons/compress/archivers/ArchiveOutputStream.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveEntry.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveOutputStream.java, src/test/java/org/apache/commons/compress/archivers/ZipTestCase.java
Add `Path` support to `ZipArchiveOutputStream` with an eye on implementing additional `ArchiveOutputStream.createArchiveEntry(Path, String,
LinkOption...)` methods in a later PR if this one is OK.
=> Add Path support to ZipArchiveOutputStream

src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveOutputStream.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipFileTest.java
Add `writePreamble` to `ZipArchiveInputStream`. This is used to create self-extracting zip.
=> COMPRESS-550 : add writePreamble to ZipArchiveInputStream

src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveInputStream.java, src/test/java/org/apache/commons/compress/archivers/tar/SparseFilesTest.java
Also some unit test cleanup to use assumeTrue/assumeFalse with the OS check. Now tests will be shown as skipped instead of success when they are not run.
=> COMPRESS-560: Do not return false if the entry is a tar sparse entry

src/test/java/org/apache/commons/compress/archivers/tar/SparseFilesTest.java
As discussed in https://github.com/apache/commons-compress/pull/113 the problem can no longer be seen in newer Ubuntu versions
=> COMPRESS-559: Extract sparsefile-0.1 also on Linux

src/main/java/org/apache/commons/compress/compressors/zstandard/ZstdCompressorInputStream.java, src/test/java/org/apache/commons/compress/compressors/zstandard/ZstdCompressorInputStreamTest.java
Add `BufferPool` as a configuration of `ZstdCompressorInputStream`
=> OMPRESS-565 : add BufferPool support in zstd

src/main/java/org/apache/commons/compress/archivers/zip/X0017_StrongEncryptionHeader.java
An empty loop in `X0017_StrongEncryptionHeader#parseCentralDirectoryFormat` can be made to run through 2^48 iterations, taking about 4 seconds on my machine, on crafted input. Since it has no side effects, it can be safely removed.
=> Remove empty loop in X0017_StrongEncryptionHeader

src/main/java/org/apache/commons/compress/archivers/zip/Zip64Mode.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveOutputStream.java, src/test/java/org/apache/commons/compress/archivers/zip/Zip64SupportIT.java
Add a new AlwaysWithComestibles in Zip64Mode, this is a compromise for some libraries including 7z and Expand-Archive Powershell utility(and likely Excel).
With `Zip64Mode.AlwaysWithComestibles`, the following fields in Central File Header will be set as needed:
1. disk number offset in split zip
2. relative offset of LFH
3. relative header offset in zip64 extra
4. disk number start in zip64 extra
These changes are consistent with commit `2b7281`.
It would be good if the generated file in test could tested by Expand-Archive or 7z, but I didn't find a way to detect them in Java.
It's welcome for suggestions about the name `Zip64Mode.AlwaysWithComestibles`  :)
See [COMPRESS-565](https://issues.apache.org/jira/projects/COMPRESS/issues/COMPRESS-565?filter=allissues&orderby=created+DESC%2C+prio …
=> COMPRESS-565 : add a new AlwaysWithCompatibility in Zip64Mode

src/main/java/org/apache/commons/compress/utils/IOUtils.java, src/test/java/org/apache/commons/compress/utils/IOUtilsTest.java
See https://issues.apache.org/jira/browse/COMPRESS-584
=> [COMPRESS-584] Fix IOUtils.readRange() can read more from a channel than asked for

src/main/java/org/apache/commons/compress/archivers/sevenz/SevenZFile.java
`CharsetEncoder` is not thread safe. Due to shared `PASSWORD_ENCODER`, problems may occur when encoding 7z file passwords in parallel. The UTF-16LE encoder rarely changes the state, so problems are rare, but the problem is real: When processing unicode surrogate pairs, the Encoder needs to store the state internally.
`Charset.encode` will cache a thread local encoder, so it is reasonable to use it directly.
=> Fix thread safety issues when encoding 7z password

src/main/java/org/apache/commons/compress/compressors/bzip2/BlockSort.java
The existing `BlockSort#med3`  function is comparing byte values, which are signed. This seems off to me, since the main calling loop appears to be handling these bytes as (non-negative) 8-bit ints. Also the original C code appears to use unsigned char values (e.g. https://github.com/centricular/bzip2/blob/35e7280360320787d09a2419e0f5a1863feb8a34/blocksort.c#L583).
This PR changes `BlockSort#med3` to accept int arguments and the caller to pass non-negative 8-bit values. I'm not really familiar enough with bzip2 to judge the impact, or to select a sample input for which this might matter. Hopefully someone more knowledgeable can weigh in.
=> bzip2: calculate median-of-3 on unsigned values

src/main/java/org/apache/commons/compress/archivers/dump/DumpArchiveEntry.java, src/main/java/org/apache/commons/compress/archivers/sevenz/Coders.java, src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveEntry.java, src/main/java/org/apache/commons/compress/archivers/zip/X7875_NewUnix.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveEntry.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveInputStream.java, src/main/java/org/apache/commons/compress/compressors/lz4/FramedLZ4CompressorInputStream.java, src/main/java/org/apache/commons/compress/compressors/snappy/SnappyCompressorInputStream.java
* Simplify conditions
* Make final var
=> Minor changes

README.md, pom.xml
COMPRESS-604 might be related to this.
I wasn't able to reproduce it, but I can confirm the build is currently not compatible with Java 8 when building on Java 9+ because the --release compiler option is set to 9, but not because of the reason pointed in COMPRESS-604.
Let me know if that doesn't work for some reason.
The build seems to work fine on JDK 17, so I removed the message about it not working on JDK 14+ from the README.
=> COMPRESS-604: Ensure compatibility with Java 8

src/test/java/org/apache/commons/compress/archivers/LongPathTest.java, src/test/java/org/apache/commons/compress/archivers/LongSymLinkTest.java, src/test/java/org/apache/commons/compress/harmony/pack200/tests/ArchiveTest.java, src/test/java/org/apache/commons/compress/harmony/pack200/tests/BHSDCodecTest.java, src/test/java/org/apache/commons/compress/harmony/pack200/tests/CodecEncodingTest.java, src/test/java/org/apache/commons/compress/harmony/pack200/tests/CodecTest.java, src/test/java/org/apache/commons/compress/harmony/pack200/tests/NewAttributeBandsTest.java, src/test/java/org/apache/commons/compress/harmony/pack200/tests/PackingOptionsTest.java, src/test/java/org/apache/commons/compress/harmony/pack200/tests/PopulationCodecTest.java, src/test/java/org/apache/commons/compress/harmony/pack200/tests/RunCodecTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/AbstractBandsTestCase.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/ArchiveTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/AttributeLayoutMapTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/AttributeLayoutTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/BandSetTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/BcBandsTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/CPUTF8Test.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/ClassBandsTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/CodeAttributeTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/ICTupleTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/NewAttributeBandsTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/SegmentConstantPoolArrayCacheTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/SegmentConstantPoolTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/SegmentOptionsTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/SegmentTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/SegmentUtilsTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/bytecode/ByteCodeTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/bytecode/ClassFileEntryTest.java, src/test/java/org/apache/commons/compress/harmony/unpack200/tests/bytecode/ConstantPoolTest.java, src/test/java/org/apache/commons/compress/java/util/jar/Pack200Test.java
Most tests are replaced with simple JUnit 5 tests. A small number of tests were migrated to parameterized tests.
=> Replace JUnit 3 with JUnit 5

pom.xml, src/main/java/org/apache/commons/compress/archivers/cpio/CpioArchiveEntry.java, src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveEntry.java, src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveOutputStream.java, src/main/java/org/apache/commons/compress/archivers/zip/X000A_NTFS.java, src/main/java/org/apache/commons/compress/archivers/zip/X5455_ExtendedTimestamp.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveEntry.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveOutputStream.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipUtil.java, src/main/java/org/apache/commons/compress/utils/TimeUtils.java, src/test/java/org/apache/commons/compress/archivers/jar/JarArchiveOutputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/zip/X5455_ExtendedTimestampTest.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipArchiveEntryTest.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipArchiveInputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipUtilTest.java, src/test/java/org/apache/commons/compress/utils/TimeUtilsTest.java
https://issues.apache.org/jira/browse/COMPRESS-613
This adds support for extra time data (InfoZip and NTFS Extra fields) to Zip archives.
This supports both reading and writing to these fields automatically, including when creating a ZipArchiveEntry from an existing file on the disk, with proper fall backs.
Additionally:
1. Works around a bug involving Integer Overflow in Java 8 and Zip archives: https://bugs.openjdk.org/browse/JDK-8130914
2. Consolidates a few more time conversions into TimeUtils
3. Works around an oversight in Java 8 where the NTFS fields on Zip archives are only read to the precision of microseconds instead of their maximum of 100ns.
Currently, it's missing a few test cases for reading/writing, though I have tested them myself. Submitting for this review because the …
=> COMPRESS-613: Support for extra time data in Zip archives

src/main/java/org/apache/commons/compress/harmony/unpack200/FileBands.java
The Pack200 decompressor expects `read` to always return the amount of bytes it requested. This is *usually* true for raw input streams, such as File or ByteArray, but breaks down when combined with other block-based decompressors. For example, combining an LZMAInputStream with a Pack200 decompressor results in an error similar to the following if a file falls between block boundaries:
```
Exception in thread "main" org.apache.commons.compress.harmony.pack200.Pack200Exception: Expected to read 48873 bytes but read 3274
at org.apache.commons.compress.harmony.unpack200.FileBands.processFileBits(FileBands.java:87)
at org.apache.commons.compress.harmony.unpack200.Segment.readSegment(Segment.java:460)
at org.apache.commons.compress.harmony.unpack200.Segment.unpackRead(Segment.java:514)
at …
```
=> pack200: Fix FileBands misusing InputStream#read(byte[])

src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveEntry.java, src/test/java/org/apache/commons/compress/ChainingTestCase.java, src/test/java/org/apache/commons/compress/archivers/TarTestCase.java, src/test/java/org/apache/commons/compress/archivers/tar/FileTimesIT.java, src/test/java/org/apache/commons/compress/archivers/tar/SparseFilesTest.java, src/test/java/org/apache/commons/compress/archivers/tar/TarArchiveEntryTest.java, src/test/java/org/apache/commons/compress/archivers/tar/TarArchiveInputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/tar/TarArchiveOutputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/tar/TarFileTest.java
Hi.
I'm making a tar compressing tool.
And I need to know what the original flag of a tar entry I read, otherwise I would make it changed in the decompressed result...
=> COMPRESS-641: add getLinkFlag for TarArchiveEntry

src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveOutputStream.java, src/test/java/org/apache/commons/compress/archivers/tar/TarArchiveOutputStreamTest.java
I wrote a test to reproduce the issue, writing to a `NullOutputStream`, but that turned out to be really slow due to the forced 512 bytes chunking. So I opted to not include that.
```java
@Test
public void testWritingBigFile() throws Exception {
final TarArchiveEntry t = new TarArchiveEntry("foo");
t.setSize((Integer.MAX_VALUE + 1L) * TarConstants.DEFAULT_RCDSIZE);
final TarArchiveOutputStream tos = new TarArchiveOutputStream(NullOutputStream.NULL_OUTPUT_STREAM);
tos.setBigNumberMode(TarArchiveOutputStream.BIGNUMBER_POSIX);
tos.putArchiveEntry(t);
byte[] bytes = new byte[TarConstants.DEFAULT_RCDSIZE];
for (int i = 0; i < Integer.MAX_VALUE; i++) {
tos.write(bytes);
}
tos.closeArchiveEntry();
tos.close();
}
```
=> COMPRESS-642 Integer overflow ArithmeticException in TarArchiveOutputStream

src/main/java/org/apache/commons/compress/compressors/lz4/FramedLZ4CompressorOutputStream.java, src/test/java/org/apache/commons/compress/compressors/lz4/FramedLZ4CompressorRoundtripTest.java
Fixed lz4 write so it no longer throws an IndexOutOfBoundsException when data is larger than Block size. Test was added. [COMPRESS-650](https://issues.apache.org/jira/browse/COMPRESS-650)
=> Fixed lz4 write so it no longer throws an IndexOutOfBoundsException

src/main/java/org/apache/commons/compress/utils/OsgiUtils.java
`org.apache.commons.compress.utils.OsgiUtils`, introduced by commit 30a7750, calls `OsgiUtils.class.getClassLoader()`.
This method can return `null` if the class is loaded by the bootstrap class loader.
When one of my CLI tools, which bundles commons-compress, used the `-Xbootclasspath/a` option for faster startup time, it started throwing a `NullPointerException` after upgrading commons-compress from 1.20 to 1.21. 
```
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.lang.Class.getClassLoader()" is null
at org.apache.commons.compress.utils.OsgiUtils.<clinit>(OsgiUtils.java:31)
```
This PR adds a null check for the class loader to avoid the `NullPointerException`.
=> Add a null check for the class loader of OsgiUtils

src/main/java/org/apache/commons/compress/compressors/snappy/FramedSnappyCompressorOutputStream.java, src/test/java/org/apache/commons/compress/compressors/snappy/FramedSnappyCompressorInputStreamTest.java
Fix and tests for https://issues.apache.org/jira/browse/COMPRESS-655.
=> [COMPRESS-655] FramedSnappyCompressorOutputStream produces incorrect output when writing a large buffer

src/main/java/org/apache/commons/compress/archivers/zip/FileRandomAccessOutputStream.java, src/main/java/org/apache/commons/compress/archivers/zip/RandomAccessOutputStream.java, src/main/java/org/apache/commons/compress/archivers/zip/SeekableChannelRandomAccessOutputStream.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveOutputStream.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipFile.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipIoUtil.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipSplitOutputStream.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipSplitReadOnlySeekableByteChannel.java, src/test/java/org/apache/commons/compress/archivers/ZipTest.java, src/test/java/org/apache/commons/compress/archivers/zip/FileRandomAccessOutputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/zip/RandomAccessOutputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/zip/SeekableChannelRandomAccessOutputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipArchiveOutputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipIoUtilTest.java, src/test/java/org/apache/commons/compress/utils/ZipSplitReadOnlySeekableByteChannelTest.java
Updates local file header metadata even for split archive, so it's readable by `zip -FF` utility.
=> COMPRESS-653: Fix split archive updating incorrect file

src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveInputStream.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipArchiveInputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipFileTest.java
`zip` can ignore any garbage at the beginning of file up to certain size.  This is supported in `ZipFile` but not in `ZipArchiveInputStream`.  This PR fixes that, including correct check for empty archive.
=> Support preamble garbage in ZipArchiveInputStream

src/main/java/org/apache/commons/compress/archivers/zip/ZipUtil.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipUtilTest.java
Since COMPRESS-613, we add an 'extra time data' field when the ZIP entry timestamp is outside the range the DOS timestamp used in other parts of the header can handle.
Before, it incorrectly also added this header when the ZIP entry timestamp was exactly the lowest possible timestamp expressable as a DOS timestamp.
This had the consequence that, when reading a ZIP file with such entries and writing it back again, ZipEntry would 'invent' an 'extra time data' field where none was needed.
With this change, it correctly considers the lowest expressable date as expressable, and avoids inventing the extra time data field in this case.
=> [COMPRESS-658] Fix formatting the lowest expressable DOS time

src/main/java/org/apache/commons/compress/archivers/zip/AsiExtraField.java, src/main/java/org/apache/commons/compress/archivers/zip/ExtraFieldUtils.java, src/main/java/org/apache/commons/compress/archivers/zip/JarMarker.java, src/main/java/org/apache/commons/compress/archivers/zip/X0014_X509Certificates.java, src/main/java/org/apache/commons/compress/archivers/zip/X0015_CertificateIdForFile.java, src/main/java/org/apache/commons/compress/archivers/zip/X0016_CertificateIdForCentralDirectory.java, src/main/java/org/apache/commons/compress/archivers/zip/X0017_StrongEncryptionHeader.java, src/main/java/org/apache/commons/compress/archivers/zip/X0019_EncryptionRecipientCertificateList.java, src/main/java/org/apache/commons/compress/archivers/zip/X7875_NewUnix.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveEntry.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipSplitReadOnlySeekableByteChannel.java, src/test/java/org/apache/commons/compress/archivers/tar/FileTimesIT.java
As of today to make [compress] run on native-image (GraalVM) you must reister all classes in IMPLEMENTATIONS map. With this PR this is no more needed and [compress] zip support comes OOTB.
=> Drop reflection from ExtraFieldUtils static initialization

src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveInputStream.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipArchiveInputStreamTest.java
Fix regression error in case when getNextEntry() method is invoked on empty file (zero size) to get first entry. Till version 1.25.0, null value was returned (like is done in standard java ZipInputStream too). The regression was caused by implementing 'Support preamble garbage in ZipArchiveInputStream' feature (PR 471).
- https://github.com/apache/commons-compress/pull/471
=> COMPRESS-664 - return null value from getNextEntry() for empty file

src/test/java/org/apache/commons/compress/archivers/tar/TarUtilsTest.java, src/test/java/org/apache/commons/compress/compressors/FramedSnappyTest.java, src/test/java/org/apache/commons/compress/compressors/lz4/BlockLZ4CompressorRoundtripTest.java, src/test/java/org/apache/commons/compress/compressors/lz4/FactoryTest.java, src/test/java/org/apache/commons/compress/compressors/lz4/FramedLZ4CompressorRoundtripTest.java, src/test/java/org/apache/commons/compress/compressors/snappy/SnappyRoundtripTest.java, src/test/java/org/apache/commons/compress/compressors/zstandard/ZstdRoundtripTest.java
This found a bug in the tests. Also, unit tests and benchmarks are different things. @garydgregory
=> Remove unused variables in tests

src/main/java/org/apache/commons/compress/compressors/gzip/GzipCompressorInputStream.java
Update Javadoc description for GzipCompressorInputStream.
See https://issues.apache.org/jira/browse/COMPRESS-685
=> [COMPRESS-685] Update Javadoc description for GzipCompressorInputStream.

src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveOutputStream.java, src/test/java/org/apache/commons/compress/archivers/ZipTest.java
This allows users to add manually compressed raw data to the zip file under an unsupported compression method (e.g., XZ) or encrypt method.
Sample usage:
```kotlin
val data = "hello world".toByteArray()
ZipArchiveOutputStream(File("test.zip")).use { zip ->
val entry = ZipArchiveEntry("test")
entry.method = ZipMethod.XZ.code
entry.crc = CRC32().apply { update(data) }.value
ByteArrayOutputStream().use { os ->
XZCompressorOutputStream(os).use {
it.write(data)
}
entry.size = data.size.toLong()
entry.compressedSize = os.size().toLong()
zip.addRawArchiveEntry(entry, ByteArrayInputStream(os.toByteArray()))
}
}
```
Previously these codes would throw an exception about the unsupported compression method.
=> ZipArchiveOutputStream.addRawArchiveEntry() should check is2PhaseSource

src/main/java/org/apache/commons/compress/archivers/ArchiveException.java, src/main/java/org/apache/commons/compress/archivers/ArchiveStreamFactory.java, src/main/java/org/apache/commons/compress/compressors/CompressorException.java, src/main/java/org/apache/commons/compress/compressors/CompressorStreamFactory.java, src/test/java/org/apache/commons/compress/archivers/ArchiveStreamFactoryTest.java, src/test/java/org/apache/commons/compress/compressors/DetectCompressorTest.java
See https://github.com/apache/httpcomponents-client/pull/580, specifically https://github.com/apache/httpcomponents-client/pull/580#pullrequestreview-2437118648
- `ArchiveException` extends `IOException`
- `CompressorException` extends `IOException`
=> Extend IOException

src/main/java/org/apache/commons/compress/utils/IOUtils.java, src/test/java/org/apache/commons/compress/utils/IOUtilsTest.java
When I was trying to move away from commons-io and commons-lang in my fork, I noticed some subtle behavior changes in IOUtils , but the description was not updated in time.
While I think it would be best to revert the code to restore the behavior, I figured that upstream might not be willing to continue maintaining the deprecated code, so I just updated the documentation to match the behavior.
=> Update outdated descriptions in IOUtils and IOUtilsTest

src/main/java/org/apache/commons/compress/archivers/zip/ZipEightByteInteger.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipEightByteIntegerTest.java
Use unsigned long instead of BigInteger to simplify code and improve performance.
=> Optimizing ZipEightByteInteger

src/main/java/org/apache/commons/compress/compressors/gzip/GzipParameters.java, src/test/java/org/apache/commons/compress/compressors/gzip/GzipParametersTest.java
When gzip parameters' filename or comment are encoded into bytes, no verification was made to avoid the \0 that internally terminates those gzip fields.
Thus, the string argument could have a \0, and/or encode into bytes that have a \0 (like with UTF-16 charsets).
This would silently corrupt the gzip member, as a reader would prematurely stop reading the filename or comment and begin reading the next piece, either the comment but inevitably the deflate stream, which would fail.
I thought also about limiting the length on write but the gzip spec has no limit. Limiting length on read (to protect memory) would be imposing an arbitrary limit too, like some gzip tools do. Either way, it would have to be an option like the charset on write, and it would be unusual to ask for such option on the …
=> Throw an IllegalArgumentException when a file name or comment in gzip parameters encodes to a byte array with a 0 byte

src/main/java/org/apache/commons/compress/archivers/zip/ZipMethod.java
Now that `https://www.winzip.com/wz54.htm` is redirected to the winzip product page, we should update these links.
=> Update outdated links in Javadoc

src/main/java/org/apache/commons/compress/compressors/gzip/GzipCompressorInputStream.java, src/main/java/org/apache/commons/compress/compressors/gzip/GzipCompressorOutputStream.java
Fix the gzip compressor inputstream and outputstream incorrect MTIME value which is already in seconds.
They should not divide or multiply by 1000.
=> (doc) fix gzip compressor incorrect MTIME value which is already in seconds

src/main/java/org/apache/commons/compress/compressors/gzip/GzipCompressorInputStream.java, src/main/java/org/apache/commons/compress/compressors/gzip/GzipCompressorOutputStream.java, src/main/java/org/apache/commons/compress/compressors/gzip/GzipParameters.java, src/test/java/org/apache/commons/compress/compressors/gzip/GzipCompressorOutputStreamTest.java
Given the boolean to generate the header CRC in the gzip parameters, the GzipCompressorOutputStream will
compute and add the CRC16 (actually low 16 bits of the CRC32) of the headers, as per the RFC.
The GzipCompressorInputStream is still handling the presence of HCRC but still not computing nor checking it,
because this would be too much a risk of regression. It will however raise the HCRC boolean in the loaded gzip parameters
to signal it was seen.
=> Optionally add FHCRC to GZIP header.

pom.xml, src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveInputStream.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipArchiveInputStreamTest.java
Exposed the instantiation of Zstd InputStream. This should give the ability to override and use a different Zstd compressor library.
=> [COMPRESS-695] Ability to use different InputStreams for Zstd

src/main/java/org/apache/commons/compress/archivers/zip/ZipFile.java, src/main/java/org/apache/commons/compress/harmony/unpack200/bytecode/Attribute.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipFileTest.java
Adjusted the ZipFile and the Builder. Added a Test for checking both.
Jira: https://issues.apache.org/jira/browse/COMPRESS-695
=> [COMPRESS-695] Configure ZipFile with a custom Zstd input stream implementation

src/main/java/org/apache/commons/compress/archivers/sevenz/SevenZFile.java, src/test/java/org/apache/commons/compress/archivers/sevenz/SevenZFileTest.java
Thanks for your contribution to [Apache Commons](https://commons.apache.org/)! Your help is appreciated!
Before you push a pull request, review this list:
In version 1.27.1 of Apache Commons Compress, the `buildDecodingStream()` method did not pass the `countThreshold ` parameter into the `ChecksumInputStream` constructor, resulting in the `getRemaining()` method of `ChecksumInputStream` returning an incorrect number of remaining bytes. This will affect `SevenZfile` # `getInputStream()` 's judgment of `hasCurrentIndexBeeReyad()` and `skipEnteriesWhenNeed()` in random access mode, resulting in the system being unable to determine whether the current entry has been read, and re extracting the entire folder content from the file header every time, seriously affecting performance. By …
=> [COMPRESS-702] Performance issue in SevenZFile

src/main/java/org/apache/commons/compress/archivers/tar/TarUtils.java, src/test/java/org/apache/commons/compress/archivers/tar/TarUtilsTest.java
The refactoring in #684 (never released) inadvertently dropped a critical part of long file name handling: names must be read incrementally to prevent excessive memory allocation if an entry is corrupted.
This change restores the previous safe behavior and adds two unit tests to ensure:
* POSIX and NTFS file names up to the maximum allowed length are handled correctly.
* Corrupted entries are detected and throw an `ArchiveException`.
Before you push a pull request, review this list:
=> fix: Restore incremental file name handling

src/main/java/org/apache/commons/compress/archivers/arj/ArjArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/cpio/CpioArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/dump/DumpArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/jar/JarArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveInputStream.java, src/test/java/org/apache/commons/compress/LegacyConstructorsTest.java, src/test/java/org/apache/commons/compress/archivers/ar/ArArchiveInputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/arj/ArjArchiveInputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/cpio/CpioArchiveInputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/dump/DumpArchiveInputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/jar/JarArchiveInputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/tar/TarArchiveInputStreamTest.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipArchiveInputStreamTest.java
This change ensures that behavior of legacy constructors remains consistent with version `1.28.0` while paving the way for their eventual removal.
**Key changes:**
* Introduces a new `LegacyConstructorsTest` class that verifies the parameter values of *deprecated* constructors. *Rationale:* this provides explicit coverage and will allow us to remove both the constructors and their tests in one step when deprecations are finalized.
* Adds equivalent test cases for non-deprecated single-argument constructors in their corresponding test classes.
* Makes the constructor of `TarArchiveInputStream.Builder` private, aligning it with the visibility of other builder constructors.
* Fixes Javadoc on deprecated constructors, which previously (incorrectly) suggested using private `Builder()` …
=> tests: Add coverage for deprecated and single-argument constructors

pom.xml, src/changes/changes.xml, src/main/java/org/apache/commons/compress/archivers/tar/TarUtils.java, src/test/java/org/apache/commons/compress/archivers/tar/TarUtilsTest.java
`TarUtils` already had a private constructor and was only used within the `o.a.c.compress.archivers.tar` package. This PR makes the class explicitly final and simplifies its internal API:
* Mark `TarUtils` as `final`.
* Change `protected` methods to package-private (they were never usable outside the package due to the private constructor).
* Remove deprecated non-`public` methods.
* Simplify `parsePaxHeaders`:
* Require a non-negative `headerSize`. The special value `-1` (“unlimited”) was only used in tests.
* Update tests to supply a valid `headerSize`.
* Standardize error handling for invalid PAX 0.0 sparse records: all parsing errors now throw `ArchiveException` (previously one case threw `IOException`).
A changelog entry is included even though these are internal changes, to give …
=> remove: make `TarUtils` final and clean up internal methods

src/changes/changes.xml, src/main/java/org/apache/commons/compress/archivers/AbstractArchiveBuilder.java, src/main/java/org/apache/commons/compress/archivers/ArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/Lister.java, src/main/java/org/apache/commons/compress/archivers/ar/ArArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/arj/ArjArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/cpio/CpioArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/dump/DumpArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/examples/Expander.java, src/main/java/org/apache/commons/compress/archivers/sevenz/SevenZFile.java, src/main/java/org/apache/commons/compress/archivers/tar/AbstractTarBuilder.java, src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/tar/TarFile.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveInputStream.java, src/main/java/org/apache/commons/compress/archivers/zip/ZipFile.java, src/test/java/org/apache/commons/compress/LegacyConstructorsTest.java, src/test/java/org/apache/commons/compress/archivers/TarTest.java, src/test/java/org/apache/commons/compress/archivers/examples/ExpanderTest.java, src/test/java/org/apache/commons/compress/archivers/sevenz/SevenZFileTest.java, src/test/java/org/apache/commons/compress/archivers/tar/BigFilesIT.java, src/test/java/org/apache/commons/compress/archivers/tar/SparseFilesTest.java, src/test/java/org/apache/commons/compress/archivers/tar/TarFileTest.java, src/test/java/org/apache/commons/compress/archivers/zip/UTF8ZipFilesTest.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipFileIgnoringLocalFileHeaderTest.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipFileTest.java, src/test/java/org/apache/commons/compress/archivers/zip/ZipMemoryFileSystemTest.java
This PR introduces a new `AbstractArchiveBuilder`, which serves as a shared foundation for all archive input streams, including `SevenZFile`, `TarFile`, and `ZipFile`.
This refactoring also leverages the new `ChannelOrigin` from Commons IO 2.21.0, streamlining the builder implementations for `SevenZFile`, `TarFile`, and `ZipFile`.
* **Constructor unification:** All constructors now delegate to a single constructor that accepts a builder.
* **Resource safety:** If an error occurs during construction (or within the builder’s `get()` method), the underlying resource is now always closed. Previously, resources provided via `SeekableByteChannel` were not closed on error, potentially leaving channels in an incoherent state.
* **Deprecation cleanup:** All references to deprecated constructors …
=> Add `AbstractArchiveBuilder` for unified archiver support
